name: Self-Hosted Runner Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Run a command
        run: |
             echo "Self-hosted runner is working!"
             mkdir clone_repo
             git clone https://github.com/Rahulram2000/Sample.git 
